### PR TITLE
Add Remaining Adventure TOCs

### PR DESCRIPTION
**Pull request by dconman**
I scraped this data off the various adventure pages.

### CODE REVIEW

**Comment by emfmesquita** [comment]
Its working like a charm. Tell me when you want to merge it. Last time I did not even ask if you wanted to make changes before merge XD.

The only problem I see in this new feature, is not a problem of itself, but it aggravates an existing problem of DDB. Some entries could not be accessed on side menu for chapters with too many entries. Specially on smaller resolutions. For example, even from 1080 x 1920 in Out of the Abyss the side menu overflows the screen and Appendix D is not visible. We probably can find a solution to this later.

Do you have all the adventures? Btw what is your username on DDB XD? If you want to send me a pm on DDB (I am Kabalistus there).

**Comment by dconman** [comment]
I'm almost done with the rule books. If you wait a second we can merge it all in together. I was thinking adding separate scrolling to the sidebar might not be too hard. Another issue is that links to maps only show up in the side menu if the current page has a map on it. I'm assuming that there is a check that says "If there are no maps on this page, don't check the side menu".

I'm dconman2 on DDB, I'll PM you.

**Comment by dconman** [comment]
Okay, rulebooks are added. I have not thoroughly checked all 19 books, but so far I haven't found any issues. I'll look into potentially adding a separate scrollbar to the TOC next.

**Comment by emfmesquita** [comment]
Hi! The only thing I have found it is that Mordenkainen's and Xanathar's have empty subsections. If I remember correctly at least Mordenkainen's has small changes on toc structure, not sure if that is the case. 

Also just thought now, I hope we don't have problems ToS problems with session titles XD. Maybe we should send a message to BadEye just to make sure. If he does not allow it, we can use the scrape in runtime and make a local cache on background scripts. I already do that to fasten map tooltips parse.

**Comment by dconman** [comment]
I spent some time fixing the data, then realized we should probably ask first. I've included the script I used to scrape, but it's not quite integrated into the application (I just ran it in my browser)

**Comment by emfmesquita** [comment]
The scroll is perfect! Also the current session open was an important addition. We may even add "border-left-color: #47D18C;" to the current chapter ".quick-menu-item-label", so this way it is still possible to know the current chapter even if the user collapses the menu. 

About the map links of other chapters don't worry I will fix this weekend. 

May I send BadEye the PM or did you already?

**Comment by dconman** [comment]
I have not. Go ahead an send it. I'm worried about the performance on this, as it does take it a while to load. I was thinking the same thing about the currently active chapter, it should be pretty easy to do.

**Pull request merged**
